### ISSUE TITLE
Figure out what upgrades we need & to represent upgrades on character

### ISSUE THREAD

**Issue by mpleclai** [HuskyGameDev/2018-team1#17]
Ex. pogo leg -> jump
Ex. rocket leg -> double jump

- move left
- sliding
- etc.

**Comment by paulwrubel** [comment]
1) Peg Leg -> Removeable with regular leg
2) Eye Patch -> Removable with normal eye
3) Peg Leg w/ Hacked together rocket booster on bottom (double jump)
4) "Slide boots" (just different color boots) indicating you can now slide / crouch
